name: Feature Tests

env:
  SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
  JWT_ACCESS_TOKEN_SECRET: ${{secrets.JWT_ACCESS_TOKEN_SECRET}}
  JWT_REFRESH_TOKEN_SECRET: ${{secrets.JWT_REFRESH_TOKEN_SECRET}}
  MONGODB_USER: ${{secrets.MONGODB_USER}}
  MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
  MONGODB_CLUSTER: ${{secrets.MONGODB_CLUSTER}}
  NEXT_PUBLIC_AUTOMATIC_MONGODB_DATABASE: ${{secrets.NEXT_PUBLIC_AUTOMATIC_MONGODB_DATABASE}}
  POSTGRES_DATABASE_URL: ${{secrets.POSTGRES_DATABASE_URL}}
  DISCORD_AUTH_URL: ${{secrets.DISCORD_AUTH_URL}}
  DISCORD_TOKEN_URL: ${{secrets.DISCORD_TOKEN_URL}}
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
  DISCORD_CALLBACK_URL: ${{secrets.DISCORD_CALLBACK_URL}}

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16.17.1"
      - name: Install modules
        run: yarn
      - name: API
        run: yarn test:api
